# Generated by Django 3.1 on 2020-09-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('check', models.BooleanField(verbose_name='Проверяется')),
                ('url_status', models.BooleanField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
