# Generated by Django 3.1 on 2020-09-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ref_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='secret_key',
        ),
    ]
